@startuml
!include <tupadr3/common>
!include <tupadr3/font-awesome/cogs>
!include <tupadr3/font-awesome/database>
!include <tupadr3/font-awesome/sitemap>
!include <tupadr3/font-awesome/code>

skinparam rectange {
  BorderColor black
  RoundCorner 20
}
skinparam defaultTextAlignment center
skinparam shadowing false

title Chomsky-Hierarchie

rectangle "Typ-0\n<$cogs>\nRekursiv aufzählbar\n(Turingmaschinen)" as Typ0 #caf0f8 {
  rectangle "Typ-1\n<$database>\nKontextsensitive Sprachen\n(LBA)" as Typ1 #90e0ef {
    rectangle "Typ-2\n<$sitemap>\nKontextfreie Sprachen\n(Kellerautomaten)" as Typ2 #48cae4 {
      rectangle "Typ-3\n<$code>\nReguläre Sprachen\n(RegEx / DFA / NFA)" as Typ3 #0077b6
    }
  }
}
@enduml

